# fly.toml app configuration file generated for findmydeviceserver on 2025-04-20T22:42:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'findmydeviceserver'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
